### PR TITLE
fix: ignore negative delays in punctuality layer

### PR DESCRIPTION
**Pull request by oterral**
# How to

No functionnalities change , it's just a fix to be up to date with the backend.

# Others

- [x] It's not a hack or at least an unauthorized hack :).
- [x] The images added are optimized.
- [x] Everything in ticket description has been fixed.
- [x] The author of the MR has made its own review before assigning the reviewer.
- [x] The title means something for a human being and follows the [conventional commits](https://www.conventionalcommits.org/) specification.
- [x] The title contains [WIP] if it's necessary.
- [x] Labels applied. if it's a release? a hotfix?
- [x] Tests added.

### CODE REVIEW

**Comment by danji90** [comment]
@oterral It's fine I guess, but we should test again once the backend updates are deployed

**Review by danji90 — DISMISSED** [review]

**Comment by danji90** [comment]
I just noticed the linting/build is failing, so I dunno if I am testing with an old version. Please fix before merge @oterral

**Review by danji90 — CHANGES_REQUESTED** [review]
I just noticed the linting/build is failing, so I dunno if I am testing with an old version. Please fix before merge @oterral

**Comment by oterral** [comment]
@danji90  The tests works again. You've tested the good version only the tests were failing, build worked.

**Comment by danji90** [comment]
@oterral OK looks good LGTM

**Review by danji90 — APPROVED** [review]

**Pull request merged**
