### PR TITLE
Display popup when we select a station in search results

### PR DESCRIPTION
**Pull request by oterral**
Also remove  sources mapbox layer, and fix update of stations sources behavior.

### CODE REVIEW

**Comment by friedjoff** [comment]
Code looks good. In terms of UX it seems a little confusing to show the popup only once the layer is loaded. Some kind of spinner would be nice to tell the user something is going to happen. @oterral do you think thats possible?

**Comment by oterral** [comment]
Problem is we have no choice than waiting for the map is loaded before displaying the popup. 
@friedjoff  where do you want to put a spinner ?

**Comment by friedjoff** [comment]
The search result contains the coordinate, right? So we could display a popup with a spinner inside.

**Comment by oterral** [comment]
Ah ok I thought a spinner on the map. I can try to see if I find something.

**Comment by oterral** [comment]
I discuss with @mhaertwig . It's a good idea but not a high prority. So I merge .

**Pull request merged**
